// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAgreement(arg1) {
  return window['go']['main']['App']['CheckAgreement'](arg1);
}

export function ExitAppFromGo() {
  return window['go']['main']['App']['ExitAppFromGo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
